name: gh

on:
  push:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          gh config set http_unix_socket /dev/null
          (
            unset GITHUB_ACTIONS
            gh api /installation/repositories || echo $?
            gh api /user || echo $?
          ) >> $GITHUB_STEP_SUMMARY
