name: gh

on:
  push:
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          gh config set http_unix_socket /dev/null
          (
            unset GITHUB_ACTIONS
            unset CI
            gh api /installation/repositories 2>&1 || echo $?
            gh api /user 2>&1 || echo $?
          ) >> $GITHUB_STEP_SUMMARY
